version: "3.7"
    
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits: 
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200               



  web:
    depends_on:
      - db
      - elasticsearch
    build: .
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      ELASTICSEARCH_URL: elasticsearch
    volumes:
      - ".:/app"
    links: 
      - db
      - elasticsearch